<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <PackageReference Include="Dapper" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Relational" />
    <ProjectReference Include="../../BuildingBlocks/SmartSchool.Application/SmartSchool.Application.csproj" />
  </ItemGroup>
</Project>
