using Dapper;
using SmartSchool.Application.Persistence;
namespace SmartSchool.Api.Features;
public static class DashboardEndpoints
{
 public static IEndpointRouteBuilder MapDashboardEndpoints(this IEndpointRouteBuilder e)
 {
  var g=e.MapGroup("/api/dashboard").RequireAuthorization().WithTags("Dashboard");
  g.MapGet("/admin",Admin).RequireAuthorization(SmartSchool.SharedKernel.Constants.SmartSchoolPolicies.SchoolAdministration);
  g.MapGet("/student/{studentId:guid}",Student).RequireAuthorization(SmartSchool.SharedKernel.Constants.SmartSchoolPolicies.StudentSelfService);
  g.MapGet("/parent/{guardianId:guid}",Parent).RequireAuthorization(SmartSchool.SharedKernel.Constants.SmartSchoolPolicies.ParentSelfService);
  g.MapGet("/teacher/{employeeId:guid}",Teacher).RequireAuthorization(SmartSchool.SharedKernel.Constants.SmartSchoolPolicies.TeacherWorkspace);
  g.MapGet("/driver/{driverId:guid}",Driver).RequireAuthorization(SmartSchool.SharedKernel.Constants.SmartSchoolPolicies.DriverWorkspace);
  return e;
 }
 private static async Task<IResult> Admin(Guid? tenantId,SmartSchool.Application.Identity.ITenantScope scope,IDbConnectionFactory f,CancellationToken ct){const string q="""SELECT (SELECT COUNT(*) FROM student.student WHERE (@TenantId IS NULL OR tenant_id=@TenantId)) AS "Students",(SELECT COUNT(*) FROM student.guardian WHERE (@TenantId IS NULL OR tenant_id=@TenantId)) AS "Guardians",(SELECT COUNT(*) FROM hr.employee WHERE (@TenantId IS NULL OR tenant_id=@TenantId)) AS "Employees",(SELECT COUNT(*) FROM exam.exam WHERE (@TenantId IS NULL OR tenant_id=@TenantId)) AS "Exams",(SELECT COUNT(*) FROM finance.student_invoice WHERE (@TenantId IS NULL OR tenant_id=@TenantId)) AS "Invoices",(SELECT COUNT(*) FROM finance.student_invoice WHERE (@TenantId IS NULL OR tenant_id=@TenantId) AND status NOT IN ('PAID','CANCELLED')) AS "OutstandingInvoices",(SELECT COUNT(*) FROM communication.notification WHERE (@TenantId IS NULL OR tenant_id=@TenantId) AND status IN ('QUEUED','PENDING')) AS "UnreadNotifications",(SELECT COUNT(*) FROM transport.vehicle WHERE (@TenantId IS NULL OR tenant_id=@TenantId)) AS "Vehicles",(SELECT COUNT(*) FROM transport.driver WHERE (@TenantId IS NULL OR tenant_id=@TenantId)) AS "Drivers";""";return Results.Ok(await One<AdminDashboard>(q,new{TenantId=scope.Resolve(tenantId)},f,ct));}
 private static async Task<IResult> Student(Guid studentId,Guid? tenantId,SmartSchool.Application.Identity.ITenantScope scope,IDbConnectionFactory f,CancellationToken ct){const string q="""SELECT s.student_id AS "StudentId",s.student_number AS "StudentNumber",s.first_name AS "FirstName",s.last_name AS "LastName",s.status AS "Status",(SELECT COUNT(*) FROM student.student_enrollment x WHERE x.tenant_id=@TenantId AND x.student_id=s.student_id) AS "Enrollments",(SELECT COUNT(*) FROM exam.student_exam_result x WHERE x.tenant_id=@TenantId AND x.student_id=s.student_id) AS "Results",(SELECT COUNT(*) FROM finance.student_invoice x WHERE x.tenant_id=@TenantId AND x.student_id=s.student_id AND x.status NOT IN ('PAID','CANCELLED')) AS "OutstandingInvoices" FROM student.student s WHERE s.tenant_id=@TenantId AND s.student_id=@StudentId;""";var x=await One<StudentDashboard>(q,new{TenantId=scope.Resolve(tenantId),StudentId=studentId},f,ct);return x is null?Results.NotFound():Results.Ok(x);}
 private static async Task<IResult> Parent(Guid guardianId,Guid? tenantId,SmartSchool.Application.Identity.ITenantScope scope,IDbConnectionFactory f,CancellationToken ct){const string q="""SELECT g.guardian_id AS "GuardianId",g.full_name AS "FullName",g.email AS "Email",g.phone AS "Phone",(SELECT COUNT(*) FROM student.student_guardian sg JOIN student.student s ON s.student_id=sg.student_id WHERE sg.guardian_id=g.guardian_id AND s.tenant_id=@TenantId) AS "Children",(SELECT COUNT(*) FROM finance.student_invoice i JOIN student.student_guardian sg ON sg.student_id=i.student_id WHERE sg.guardian_id=g.guardian_id AND i.tenant_id=@TenantId AND i.status NOT IN ('PAID','CANCELLED')) AS "OutstandingInvoices" FROM student.guardian g WHERE g.tenant_id=@TenantId AND g.guardian_id=@GuardianId;""";var x=await One<ParentDashboard>(q,new{TenantId=scope.Resolve(tenantId),GuardianId=guardianId},f,ct);return x is null?Results.NotFound():Results.Ok(x);}
 private static async Task<IResult> Teacher(Guid employeeId,Guid? tenantId,SmartSchool.Application.Identity.ITenantScope scope,IDbConnectionFactory f,CancellationToken ct){const string q="""SELECT e.employee_id AS "EmployeeId",e.employee_number AS "EmployeeNumber",e.first_name AS "FirstName",e.last_name AS "LastName",e.status AS "Status",(SELECT COUNT(*) FROM academic.teacher_course_assignment a WHERE a.tenant_id=@TenantId AND a.employee_id=e.employee_id) AS "CourseAssignments",CAST(0 AS bigint) AS "PendingLeaves" FROM hr.employee e WHERE e.tenant_id=@TenantId AND e.employee_id=@EmployeeId;""";var x=await One<TeacherDashboard>(q,new{TenantId=scope.Resolve(tenantId),EmployeeId=employeeId},f,ct);return x is null?Results.NotFound():Results.Ok(x);}
 private static async Task<IResult> Driver(Guid driverId,Guid? tenantId,SmartSchool.Application.Identity.ITenantScope scope,IDbConnectionFactory f,CancellationToken ct){const string q="""SELECT d.driver_id AS "DriverId",d.driver_number AS "DriverNumber",d.full_name AS "FullName",d.phone AS "Phone",d.status AS "Status",d.driving_license_expires_on AS "LicenseExpiresOn",(SELECT COUNT(*) FROM transport.vehicle_driver_assignment a WHERE a.tenant_id=@TenantId AND a.driver_id=d.driver_id AND a.effective_to IS NULL) AS "ActiveVehicleAssignments" FROM transport.driver d WHERE d.tenant_id=@TenantId AND d.driver_id=@DriverId;""";var x=await One<DriverDashboard>(q,new{TenantId=scope.Resolve(tenantId),DriverId=driverId},f,ct);return x is null?Results.NotFound():Results.Ok(x);}
 private static async Task<T?> One<T>(string q,object p,IDbConnectionFactory f,CancellationToken ct){await using var c=await f.OpenConnectionAsync(ct);return await c.QuerySingleOrDefaultAsync<T>(new CommandDefinition(q,p,cancellationToken:ct));}
 public sealed record AdminDashboard(long Students,long Guardians,long Employees,long Exams,long Invoices,long OutstandingInvoices,long UnreadNotifications,long Vehicles,long Drivers);
 public sealed record StudentDashboard(Guid StudentId,string StudentNumber,string FirstName,string? LastName,string Status,long Enrollments,long Results,long OutstandingInvoices);
 public sealed record ParentDashboard(Guid GuardianId,string FullName,string? Email,string? Phone,long Children,long OutstandingInvoices);
 public sealed record TeacherDashboard(Guid EmployeeId,string EmployeeNumber,string FirstName,string? LastName,string Status,long CourseAssignments,long PendingLeaves);
 public sealed record DriverDashboard(Guid DriverId,string DriverNumber,string FullName,string? Phone,string Status,DateOnly? LicenseExpiresOn,long ActiveVehicleAssignments);
}
