using SmartSchool.SharedKernel.Constants;
using FluentValidation;
using Microsoft.EntityFrameworkCore;
using SmartSchool.Application.Http;
using SmartSchool.Application.Identity;
using SmartSchool.Application.Messaging;
using SmartSchool.Application.Persistence;
using SmartSchool.Modules.Workflow.Models;
using SmartSchool.Modules.Workflow.Persistence;
using SmartSchool.SharedKernel;
namespace SmartSchool.Modules.Workflow.Features.Approval;
public static class UpdateApproval
{
 public sealed record Request(Guid Id,Guid? TenantId,string Decision,string? Comments):IRequest<Result>;
 public sealed class Validator:AbstractValidator<Request>{public Validator(){RuleFor(x=>x.Id).NotEmpty();RuleFor(x=>x.Decision).NotEmpty().Must(x=>!string.IsNullOrWhiteSpace(x)&&(x.ToUpperInvariant() is "APPROVED" or "REJECTED"));RuleFor(x=>x.Comments).MaximumLength(2000);}}
 public interface IUpdateApproval{Task<ApprovalEntity?> GetAsync(Guid tenantId,Guid id,CancellationToken cancellationToken);Task<WorkflowInstanceEntity?> GetInstanceAsync(Guid tenantId,Guid id,CancellationToken cancellationToken);Task<List<WorkflowStepEntity>> GetStepsAsync(Guid tenantId,Guid definitionId,CancellationToken cancellationToken);Task SaveAsync(ApprovalEntity approval,WorkflowInstanceEntity instance,ApprovalEntity? next,CancellationToken cancellationToken);}
 internal sealed class Command(IWorkflowDbContext db):IUpdateApproval{public Task<ApprovalEntity?> GetAsync(Guid tenantId,Guid id,CancellationToken cancellationToken)=>db.Approvals.SingleOrDefaultAsync(x=>x.TenantId==tenantId&&x.ApprovalId==id&&x.IsActive,cancellationToken);public Task<WorkflowInstanceEntity?> GetInstanceAsync(Guid tenantId,Guid id,CancellationToken cancellationToken)=>db.WorkflowInstances.SingleOrDefaultAsync(x=>x.TenantId==tenantId&&x.WorkflowInstanceId==id&&x.IsActive,cancellationToken);public Task<List<WorkflowStepEntity>> GetStepsAsync(Guid tenantId,Guid definitionId,CancellationToken cancellationToken)=>db.WorkflowSteps.Where(x=>x.TenantId==tenantId&&x.WorkflowDefinitionId==definitionId&&x.IsActive).OrderBy(x=>x.StepOrder).ToListAsync(cancellationToken);public async Task SaveAsync(ApprovalEntity approval,WorkflowInstanceEntity instance,ApprovalEntity? next,CancellationToken cancellationToken){await using var tx=await db.Database.BeginTransactionAsync(cancellationToken);if(next is not null)await db.Approvals.AddAsync(next,cancellationToken);await db.SaveChangesAsync(cancellationToken);await tx.CommitAsync(cancellationToken);}}
 public sealed class Handler(IUpdateApproval command,IBusinessNumberGenerator numberGenerator,ITenantScope tenantScope,ICurrentUser currentUser):IRequestHandler<Request,Result>
 {public async Task<Result> HandleAsync(Request request,CancellationToken cancellationToken){var tenant=tenantScope.Resolve(request.TenantId);if(!tenant.HasValue)return Result.Failure(Error.Validation("Tenant context is required."));var approval=await command.GetAsync(tenant.Value,request.Id,cancellationToken);if(approval is null)return Result.Failure(Error.NotFound("Approval was not found."));if(!approval.Status.Equals("PENDING",StringComparison.OrdinalIgnoreCase))return Result.Failure(Error.Conflict("This approval has already been decided."));var isAssigned=currentUser.Roles.Any(r=>r.Equals(approval.AssignedRole,StringComparison.OrdinalIgnoreCase));if(!isAssigned&&!currentUser.IsSuperAdmin)return Result.Failure(Error.Forbidden("This approval is assigned to a different role."));var instance=await command.GetInstanceAsync(tenant.Value,approval.WorkflowInstanceId,cancellationToken);if(instance is null||instance.Status!="IN_PROGRESS")return Result.Failure(Error.Conflict("The workflow instance is no longer awaiting a decision."));approval.Decide(request.Decision,currentUser.UserId,request.Comments);if(request.Decision.Equals("REJECTED",StringComparison.OrdinalIgnoreCase)){instance.Reject();await command.SaveAsync(approval,instance,null,cancellationToken);return Result.Success();}var steps=await command.GetStepsAsync(tenant.Value,instance.WorkflowDefinitionId,cancellationToken);var next=steps.FirstOrDefault(x=>x.StepOrder>instance.CurrentStepOrder&&x.StepType.Equals("APPROVAL",StringComparison.OrdinalIgnoreCase));ApprovalEntity? nextApproval=null;if(next is null){instance.Complete();}else{instance.MoveToStep(next.StepOrder);var code=await numberGenerator.NextAsync("WorkflowApproval","WFA",tenant,7,cancellationToken);nextApproval=ApprovalEntity.Create(tenant.Value,instance.WorkflowInstanceId,next.WorkflowStepId,code,$"{instance.Name}: {next.Name}",next.ApproverRole!);}await command.SaveAsync(approval,instance,nextApproval,cancellationToken);return Result.Success();}}
 public static IEndpointRouteBuilder MapEndpoint(IEndpointRouteBuilder endpoints){endpoints.MapPut(ApiRoutes.EntityById(ModuleConstants.RouteSegment,"approval"),async(Guid id,Request body,IMediator mediator,CancellationToken cancellationToken)=>(await mediator.SendAsync<Request,Result>(body with{Id=id},cancellationToken)).ToHttpResult()).WithName("ProcessWorkflowApproval").WithTags(ModuleConstants.Name).RequireAuthorization();return endpoints;}
}
