<Project>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <AnalysisLevel>latest</AnalysisLevel>
    <EnforceCodeStyleInBuild>true</EnforceCodeStyleInBuild>
  </PropertyGroup>

  <ItemGroup Condition="$([System.String]::Copy('$(MSBuildProjectName)').StartsWith('SmartSchool.Modules.'))">
    <FrameworkReference Include="Microsoft.AspNetCore.App" />

    <ProjectReference Include="$(MSBuildThisFileDirectory)src/BuildingBlocks/SmartSchool.SharedKernel/SmartSchool.SharedKernel.csproj" />
    <ProjectReference Include="$(MSBuildThisFileDirectory)src/BuildingBlocks/SmartSchool.Application/SmartSchool.Application.csproj" />

    <PackageReference Include="FluentValidation" />

    <Compile Include="$(MSBuildThisFileDirectory)build/SmartSchool.AspNetCoreGlobalUsings.cs"
             Link="SmartSchool.AspNetCoreGlobalUsings.g.cs" />
  </ItemGroup>

  <ItemGroup Condition="'$(MSBuildProjectName)' == 'SmartSchool.Application'">
    <FrameworkReference Include="Microsoft.AspNetCore.App" />

    <ProjectReference Include="$(MSBuildThisFileDirectory)src/BuildingBlocks/SmartSchool.SharedKernel/SmartSchool.SharedKernel.csproj" />

    <PackageReference Include="FluentValidation" />

    <Compile Include="$(MSBuildThisFileDirectory)build/SmartSchool.AspNetCoreGlobalUsings.cs"
             Link="SmartSchool.AspNetCoreGlobalUsings.g.cs" />
  </ItemGroup>

  <ItemGroup Condition="'$(MSBuildProjectName)' == 'SmartSchool.Infrastructure'">
    <FrameworkReference Include="Microsoft.AspNetCore.App" />

    <ProjectReference Include="$(MSBuildThisFileDirectory)src/BuildingBlocks/SmartSchool.SharedKernel/SmartSchool.SharedKernel.csproj" />
    <ProjectReference Include="$(MSBuildThisFileDirectory)src/BuildingBlocks/SmartSchool.Application/SmartSchool.Application.csproj" />

    <PackageReference Include="Confluent.Kafka" />
    <PackageReference Include="Hangfire.AspNetCore" />
    <PackageReference Include="Hangfire.PostgreSql" />
    <PackageReference Include="Serilog.AspNetCore" />
    <PackageReference Include="Serilog.Enrichers.Environment" />
    <PackageReference Include="Serilog.Enrichers.Thread" />
    <PackageReference Include="Serilog.Formatting.Compact" />
    <PackageReference Include="Serilog.Sinks.Console" />

    <Compile Include="$(MSBuildThisFileDirectory)build/SmartSchool.AspNetCoreGlobalUsings.cs"
             Link="SmartSchool.AspNetCoreGlobalUsings.g.cs" />
  </ItemGroup>

  <ItemGroup Condition="'$(MSBuildProjectName)' == 'SmartSchool.Api'">
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" />
    <PackageReference Include="Microsoft.Extensions.Http.Resilience" />

    <Compile Include="$(MSBuildThisFileDirectory)build/SmartSchool.AspNetCoreGlobalUsings.cs"
             Link="SmartSchool.AspNetCoreGlobalUsings.g.cs" />
  </ItemGroup>

</Project>
