// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SmartSchool.Modules.Examinations.Persistence;

#nullable disable

namespace SmartSchool.Modules.Examinations.Persistence.Migrations.PostgreSql
{
    [DbContext(typeof(ExaminationsDbContext))]
    partial class ExaminationsDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SmartSchool.Modules.Examinations.Models.ExamEntity", b =>
                {
                    b.Property<Guid>("ExamId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("exam_id");

                    b.Property<Guid>("AcademicSystemId")
                        .HasColumnType("uuid")
                        .HasColumnName("academic_system_id");

                    b.Property<Guid>("AcademicYearId")
                        .HasColumnType("uuid")
                        .HasColumnName("academic_year_id");

                    b.Property<Guid>("CampusId")
                        .HasColumnType("uuid")
                        .HasColumnName("campus_id");

                    b.Property<Guid?>("ClassSectionId")
                        .HasColumnType("uuid")
                        .HasColumnName("class_section_id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("code");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateOnly?>("EndDate")
                        .HasColumnType("date")
                        .HasColumnName("end_date");

                    b.Property<string>("ExamTypeCode")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("exam_type_code");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("MetadataJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("metadata_json");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)")
                        .HasColumnName("name");

                    b.Property<DateOnly?>("ResultPublishDate")
                        .HasColumnType("date")
                        .HasColumnName("result_publish_date");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("row_version");

                    b.Property<DateOnly?>("StartDate")
                        .HasColumnType("date")
                        .HasColumnName("start_date");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<Guid?>("TermId")
                        .HasColumnType("uuid")
                        .HasColumnName("term_id");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("ExamId");

                    b.HasIndex("TenantId");

                    b.HasIndex("TenantId", "Code")
                        .IsUnique();

                    b.ToTable("exam", "exam");
                });

            modelBuilder.Entity("SmartSchool.Modules.Examinations.Models.ExamSubjectEntity", b =>
                {
                    b.Property<Guid>("ExamSubjectId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("exam_subject_id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("code");

                    b.Property<Guid>("CourseOfferingId")
                        .HasColumnType("uuid")
                        .HasColumnName("course_offering_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int?>("DurationMinutes")
                        .HasColumnType("integer")
                        .HasColumnName("duration_minutes");

                    b.Property<DateOnly?>("ExamDate")
                        .HasColumnType("date")
                        .HasColumnName("exam_date");

                    b.Property<Guid>("ExamId")
                        .HasColumnType("uuid")
                        .HasColumnName("exam_id");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("MetadataJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("metadata_json");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)")
                        .HasColumnName("name");

                    b.Property<decimal?>("PassingMarks")
                        .HasColumnType("numeric")
                        .HasColumnName("passing_marks");

                    b.Property<Guid?>("RoomId")
                        .HasColumnType("uuid")
                        .HasColumnName("room_id");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("row_version");

                    b.Property<TimeOnly?>("StartTime")
                        .HasColumnType("time without time zone")
                        .HasColumnName("start_time");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<decimal>("TotalMarks")
                        .HasColumnType("numeric")
                        .HasColumnName("total_marks");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("ExamSubjectId");

                    b.HasIndex("ExamId");

                    b.HasIndex("TenantId");

                    b.HasIndex("TenantId", "Code")
                        .IsUnique();

                    b.ToTable("exam_subject", "exam");
                });

            modelBuilder.Entity("SmartSchool.Modules.Examinations.Models.ExamTaskEntity", b =>
                {
                    b.Property<Guid>("ExamTaskId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("exam_task_id");

                    b.Property<DateTimeOffset>("AssignedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("assigned_at");

                    b.Property<Guid>("AssignedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("assigned_by_user_id");

                    b.Property<DateTimeOffset?>("AssignmentNotifiedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("assignment_notified_at");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<Guid?>("CompletedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("completed_by_user_id");

                    b.Property<Guid>("CourseOfferingId")
                        .HasColumnType("uuid")
                        .HasColumnName("course_offering_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset>("DueAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("due_at");

                    b.Property<Guid>("ExamId")
                        .HasColumnType("uuid")
                        .HasColumnName("exam_id");

                    b.Property<Guid>("ExamSubjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("exam_subject_id");

                    b.Property<string>("Instructions")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("instructions");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<DateTimeOffset?>("OverdueReminderSentAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("overdue_reminder_sent_at");

                    b.Property<DateTimeOffset?>("Reminder24HoursSentAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("reminder_24_hours_sent_at");

                    b.Property<DateTimeOffset?>("Reminder2HoursSentAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("reminder_2_hours_sent_at");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("row_version");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("status");

                    b.Property<string>("SubmissionContentType")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("submission_content_type");

                    b.Property<byte[]>("SubmissionFileData")
                        .HasColumnType("bytea")
                        .HasColumnName("submission_file_data");

                    b.Property<string>("SubmissionFileName")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("submission_file_name");

                    b.Property<string>("SubmissionNotes")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("submission_notes");

                    b.Property<DateTimeOffset?>("SubmittedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("submitted_at");

                    b.Property<string>("TaskType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("task_type");

                    b.Property<Guid>("TeacherCourseAssignmentId")
                        .HasColumnType("uuid")
                        .HasColumnName("teacher_course_assignment_id");

                    b.Property<Guid>("TeacherEmployeeId")
                        .HasColumnType("uuid")
                        .HasColumnName("teacher_employee_id");

                    b.Property<Guid>("TeacherUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("teacher_user_id");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)")
                        .HasColumnName("title");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("ExamTaskId");

                    b.HasIndex("ExamId");

                    b.HasIndex("ExamSubjectId");

                    b.HasIndex("TenantId", "DueAt", "Status");

                    b.HasIndex("TenantId", "ExamId", "ExamSubjectId");

                    b.HasIndex("TenantId", "TeacherUserId", "Status");

                    b.HasIndex("TenantId", "ExamSubjectId", "TeacherEmployeeId", "TaskType", "IsActive")
                        .IsUnique();

                    b.ToTable("exam_task", "exam");
                });

            modelBuilder.Entity("SmartSchool.Modules.Examinations.Models.GradeScaleEntity", b =>
                {
                    b.Property<Guid>("GradeScaleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("grade_scale_id");

                    b.Property<Guid>("CampusId")
                        .HasColumnType("uuid")
                        .HasColumnName("campus_id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("code");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<decimal?>("GradePoint")
                        .HasPrecision(4, 2)
                        .HasColumnType("numeric(4,2)")
                        .HasColumnName("grade_point");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<decimal>("MaximumPercentage")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("maximum_percentage");

                    b.Property<string>("MetadataJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("metadata_json");

                    b.Property<decimal>("MinimumPercentage")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("minimum_percentage");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)")
                        .HasColumnName("name");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("row_version");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("GradeScaleId");

                    b.HasIndex("TenantId");

                    b.HasIndex("TenantId", "Code")
                        .IsUnique();

                    b.ToTable("grade_scale", "exam");
                });

            modelBuilder.Entity("SmartSchool.Modules.Examinations.Models.StudentExamResultEntity", b =>
                {
                    b.Property<Guid>("StudentExamResultId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("student_exam_result_id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("code");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("EnteredBy")
                        .HasColumnType("uuid")
                        .HasColumnName("entered_by");

                    b.Property<Guid>("ExamSubjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("exam_subject_id");

                    b.Property<string>("Grade")
                        .HasColumnType("text")
                        .HasColumnName("grade");

                    b.Property<bool>("IsAbsent")
                        .HasColumnType("boolean")
                        .HasColumnName("is_absent");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<decimal?>("MarksObtained")
                        .HasColumnType("numeric")
                        .HasColumnName("marks_obtained");

                    b.Property<string>("MetadataJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("metadata_json");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)")
                        .HasColumnName("name");

                    b.Property<decimal?>("Percentage")
                        .HasColumnType("numeric")
                        .HasColumnName("percentage");

                    b.Property<string>("Remarks")
                        .HasColumnType("text")
                        .HasColumnName("remarks");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("row_version");

                    b.Property<Guid>("StudentId")
                        .HasColumnType("uuid")
                        .HasColumnName("student_id");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("VerifiedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("verified_by");

                    b.HasKey("StudentExamResultId");

                    b.HasIndex("ExamSubjectId");

                    b.HasIndex("TenantId");

                    b.HasIndex("TenantId", "Code")
                        .IsUnique();

                    b.ToTable("student_exam_result", "exam");
                });

            modelBuilder.Entity("SmartSchool.Modules.Examinations.Models.ExamSubjectEntity", b =>
                {
                    b.HasOne("SmartSchool.Modules.Examinations.Models.ExamEntity", null)
                        .WithMany()
                        .HasForeignKey("ExamId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("SmartSchool.Modules.Examinations.Models.ExamTaskEntity", b =>
                {
                    b.HasOne("SmartSchool.Modules.Examinations.Models.ExamEntity", null)
                        .WithMany()
                        .HasForeignKey("ExamId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SmartSchool.Modules.Examinations.Models.ExamSubjectEntity", null)
                        .WithMany()
                        .HasForeignKey("ExamSubjectId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("SmartSchool.Modules.Examinations.Models.StudentExamResultEntity", b =>
                {
                    b.HasOne("SmartSchool.Modules.Examinations.Models.ExamSubjectEntity", null)
                        .WithMany()
                        .HasForeignKey("ExamSubjectId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
