<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <PackageReference Include="Dapper" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Relational" />
    <PackageReference Include="Microsoft.Extensions.Caching.Hybrid" />
    <PackageReference Include="Microsoft.Extensions.AI" />
    <PackageReference Include="ModelContextProtocol.AspNetCore" />
    <PackageReference Include="LangChain.Core" />
    <PackageReference Include="UglyToad.PdfPig" />
    <PackageReference Include="LangChain.Providers.Ollama" />
   
  </ItemGroup>
  <ItemGroup>
  </ItemGroup>
</Project>
