namespace SmartSchool.Modules.Communication.Models;

/// <summary>Defines supported school notification events.</summary>
public enum NotificationType
{
    ExamScheduled,
    ExamStartingSoon,
    ExamResultPublished,
    TimetablePublished,
    TimetableChanged,
    ClassTimingChanged,
    EidHoliday,
    SummerVacation,
    WinterVacation,
    PublicHoliday,
    FeeDue,
    FeeOverdue,
    FeeSubmitted,
    FeePaymentConfirmed,
    FeeWaived,
    LeaveSubmitted,
    LeaveAccepted,
    LeaveRejected,
    LeaveCancelled,
    AdmissionSubmitted,
    AdmissionAccepted,
    AdmissionRejected,
    AdmissionTerminated,
    EventCreated,
    EventPostponed,
    EventCancelled,
    EventReminder,
    AttendanceAbsent,
    AttendanceLate,
    AttendanceSummary,
    AssignmentCreated,
    AssignmentDue,
    AssignmentGraded,
    AnnouncementPublished,
    EmergencyAlert,
    TransportDelay,
    TransportRouteChanged,
    ParentTeacherMeeting,
    TeacherSubstitution,
    ReportCardPublished,
    General
}
