-- SmartSchool Duende IdentityServer v8 + ASP.NET Core Identity
-- Prefer EF migration generation for production. This script documents/bootstraps the identity schema.
CREATE SCHEMA IF NOT EXISTS identity;

CREATE TABLE IF NOT EXISTS identity."Roles" (
	"Id" uuid PRIMARY KEY, "TenantId" uuid NULL, "Name" varchar(256) NULL,
	"NormalizedName" varchar(256) NULL, "ConcurrencyStamp" text NULL,
	"Description" varchar(500) NULL, "IsSystemRole" boolean NOT NULL DEFAULT false
);
CREATE UNIQUE INDEX IF NOT EXISTS "RoleNameIndex" ON identity."Roles"("NormalizedName");

CREATE TABLE IF NOT EXISTS identity."Users" (
	"Id" uuid PRIMARY KEY, "TenantId" uuid NOT NULL, "FirstName" varchar(150) NOT NULL,
	"LastName" varchar(150) NOT NULL, "DisplayName" varchar(300) NULL,
	"IsActive" boolean NOT NULL DEFAULT true, "CreatedAt" timestamptz NOT NULL DEFAULT now(),
	"UpdatedAt" timestamptz NULL, "UserName" varchar(256) NULL, "NormalizedUserName" varchar(256) NULL,
	"Email" varchar(256) NULL, "NormalizedEmail" varchar(256) NULL, "EmailConfirmed" boolean NOT NULL,
	"PasswordHash" text NULL, "SecurityStamp" text NULL, "ConcurrencyStamp" text NULL,
	"PhoneNumber" text NULL, "PhoneNumberConfirmed" boolean NOT NULL, "TwoFactorEnabled" boolean NOT NULL,
	"LockoutEnd" timestamptz NULL, "LockoutEnabled" boolean NOT NULL, "AccessFailedCount" integer NOT NULL
);
CREATE UNIQUE INDEX IF NOT EXISTS "UserNameIndex" ON identity."Users"("NormalizedUserName");
CREATE INDEX IF NOT EXISTS "EmailIndex" ON identity."Users"("NormalizedEmail");
CREATE INDEX IF NOT EXISTS "IX_Users_Tenant_Email" ON identity."Users"("TenantId","NormalizedEmail");

CREATE TABLE IF NOT EXISTS identity."UserRoles" (
	"UserId" uuid NOT NULL REFERENCES identity."Users"("Id") ON DELETE CASCADE,
	"RoleId" uuid NOT NULL REFERENCES identity."Roles"("Id") ON DELETE CASCADE,
	PRIMARY KEY("UserId","RoleId")
);
CREATE TABLE IF NOT EXISTS identity."UserClaims" (
	"Id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	"UserId" uuid NOT NULL REFERENCES identity."Users"("Id") ON DELETE CASCADE,
	"ClaimType" text NULL, "ClaimValue" text NULL
);
CREATE TABLE IF NOT EXISTS identity."RoleClaims" (
	"Id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	"RoleId" uuid NOT NULL REFERENCES identity."Roles"("Id") ON DELETE CASCADE,
	"ClaimType" text NULL, "ClaimValue" text NULL
);
CREATE TABLE IF NOT EXISTS identity."UserLogins" (
	"LoginProvider" varchar(128) NOT NULL, "ProviderKey" varchar(128) NOT NULL,
	"ProviderDisplayName" text NULL, "UserId" uuid NOT NULL REFERENCES identity."Users"("Id") ON DELETE CASCADE,
	PRIMARY KEY("LoginProvider","ProviderKey")
);
CREATE TABLE IF NOT EXISTS identity."UserTokens" (
	"UserId" uuid NOT NULL REFERENCES identity."Users"("Id") ON DELETE CASCADE,
	"LoginProvider" varchar(128) NOT NULL, "Name" varchar(128) NOT NULL, "Value" text NULL,
	PRIMARY KEY("UserId","LoginProvider","Name")
);
