-- SmartSchool UI read-model/database alignment
-- Generated from every Dapper SELECT used by module APIs.
BEGIN;
ALTER TABLE academic.academic_system ADD COLUMN IF NOT EXISTS metadata_json jsonb;
ALTER TABLE academic.academic_year ADD COLUMN IF NOT EXISTS code character varying(500);
ALTER TABLE academic.academic_year ADD COLUMN IF NOT EXISTS metadata_json jsonb;
ALTER TABLE academic.class_section ADD COLUMN IF NOT EXISTS code character varying(500);
ALTER TABLE academic.class_section ADD COLUMN IF NOT EXISTS metadata_json jsonb;
ALTER TABLE academic.class_section ADD COLUMN IF NOT EXISTS name character varying(500);
ALTER TABLE academic.course_offering ADD COLUMN IF NOT EXISTS code character varying(500);
ALTER TABLE academic.course_offering ADD COLUMN IF NOT EXISTS metadata_json jsonb;
ALTER TABLE academic.course_offering ADD COLUMN IF NOT EXISTS name character varying(500);
ALTER TABLE academic.grade_level ADD COLUMN IF NOT EXISTS metadata_json jsonb;
ALTER TABLE academic.program ADD COLUMN IF NOT EXISTS metadata_json jsonb;
ALTER TABLE academic.subject ADD COLUMN IF NOT EXISTS metadata_json jsonb;
ALTER TABLE academic.term ADD COLUMN IF NOT EXISTS metadata_json jsonb;
ALTER TABLE academic.timetable ADD COLUMN IF NOT EXISTS code character varying(500);
ALTER TABLE academic.timetable ADD COLUMN IF NOT EXISTS metadata_json jsonb;
ALTER TABLE activity.activity ADD COLUMN IF NOT EXISTS code character varying(500);
ALTER TABLE activity.activity ADD COLUMN IF NOT EXISTS metadata_json jsonb;
ALTER TABLE activity.student_activity ADD COLUMN IF NOT EXISTS code character varying(500);
ALTER TABLE activity.student_activity ADD COLUMN IF NOT EXISTS metadata_json jsonb;
ALTER TABLE activity.student_activity ADD COLUMN IF NOT EXISTS name character varying(500);
ALTER TABLE activity.student_award ADD COLUMN IF NOT EXISTS code character varying(500);
ALTER TABLE activity.student_award ADD COLUMN IF NOT EXISTS metadata_json jsonb;
ALTER TABLE activity.student_award ADD COLUMN IF NOT EXISTS name character varying(500);
ALTER TABLE ai.class_performance_insight ADD COLUMN IF NOT EXISTS code character varying(500);
ALTER TABLE ai.class_performance_insight ADD COLUMN IF NOT EXISTS metadata_json jsonb;
ALTER TABLE ai.class_performance_insight ADD COLUMN IF NOT EXISTS name character varying(500);
ALTER TABLE ai.prediction_evaluation ADD COLUMN IF NOT EXISTS code character varying(500);
ALTER TABLE ai.prediction_evaluation ADD COLUMN IF NOT EXISTS metadata_json jsonb;
ALTER TABLE ai.prediction_evaluation ADD COLUMN IF NOT EXISTS name character varying(500);
ALTER TABLE ai.prediction_evidence ADD COLUMN IF NOT EXISTS code character varying(500);
ALTER TABLE ai.prediction_evidence ADD COLUMN IF NOT EXISTS metadata_json jsonb;
ALTER TABLE ai.prediction_evidence ADD COLUMN IF NOT EXISTS name character varying(500);
ALTER TABLE ai.prediction_model ADD COLUMN IF NOT EXISTS metadata_json jsonb;
ALTER TABLE ai.student_intervention ADD COLUMN IF NOT EXISTS code character varying(500);
ALTER TABLE ai.student_intervention ADD COLUMN IF NOT EXISTS metadata_json jsonb;
ALTER TABLE ai.student_intervention ADD COLUMN IF NOT EXISTS name character varying(500);
ALTER TABLE ai.student_performance_prediction ADD COLUMN IF NOT EXISTS code character varying(500);
ALTER TABLE ai.student_performance_prediction ADD COLUMN IF NOT EXISTS metadata_json jsonb;
ALTER TABLE ai.student_performance_prediction ADD COLUMN IF NOT EXISTS name character varying(500);
ALTER TABLE ai.teaching_recommendation ADD COLUMN IF NOT EXISTS code character varying(500);
ALTER TABLE ai.teaching_recommendation ADD COLUMN IF NOT EXISTS metadata_json jsonb;
ALTER TABLE ai.teaching_recommendation ADD COLUMN IF NOT EXISTS name character varying(500);
ALTER TABLE ai.topic_performance_insight ADD COLUMN IF NOT EXISTS code character varying(500);
ALTER TABLE ai.topic_performance_insight ADD COLUMN IF NOT EXISTS metadata_json jsonb;
ALTER TABLE ai.topic_performance_insight ADD COLUMN IF NOT EXISTS name character varying(500);
ALTER TABLE ai_core.ai_execution_log ADD COLUMN IF NOT EXISTS code character varying(500);
ALTER TABLE ai_core.ai_execution_log ADD COLUMN IF NOT EXISTS metadata_json jsonb;
ALTER TABLE ai_core.ai_execution_log ADD COLUMN IF NOT EXISTS name character varying(500);
ALTER TABLE ai_core.knowledge_chunk ADD COLUMN IF NOT EXISTS code character varying(500);
ALTER TABLE ai_core.knowledge_chunk ADD COLUMN IF NOT EXISTS metadata_json jsonb;
ALTER TABLE ai_core.knowledge_chunk ADD COLUMN IF NOT EXISTS name character varying(500);
ALTER TABLE ai_core.knowledge_collection ADD COLUMN IF NOT EXISTS metadata_json jsonb;
ALTER TABLE ai_core.knowledge_document ADD COLUMN IF NOT EXISTS code character varying(500);
ALTER TABLE ai_core.knowledge_document ADD COLUMN IF NOT EXISTS metadata_json jsonb;
ALTER TABLE ai_core.knowledge_document ADD COLUMN IF NOT EXISTS name character varying(500);
ALTER TABLE ai_core.model_configuration ADD COLUMN IF NOT EXISTS metadata_json jsonb;
ALTER TABLE ai_core.model_configuration ADD COLUMN IF NOT EXISTS name character varying(500);
ALTER TABLE ai_core.prompt_template ADD COLUMN IF NOT EXISTS metadata_json jsonb;
ALTER TABLE ai_core.prompt_template ADD COLUMN IF NOT EXISTS name character varying(500);
ALTER TABLE ai_core.tool_definition ADD COLUMN IF NOT EXISTS metadata_json jsonb;
ALTER TABLE ai_tutor.generated_quiz ADD COLUMN IF NOT EXISTS code character varying(500);
ALTER TABLE ai_tutor.generated_quiz ADD COLUMN IF NOT EXISTS metadata_json jsonb;
ALTER TABLE ai_tutor.generated_quiz ADD COLUMN IF NOT EXISTS name character varying(500);
ALTER TABLE ai_tutor.learning_recommendation ADD COLUMN IF NOT EXISTS code character varying(500);
ALTER TABLE ai_tutor.learning_recommendation ADD COLUMN IF NOT EXISTS metadata_json jsonb;
ALTER TABLE ai_tutor.learning_recommendation ADD COLUMN IF NOT EXISTS name character varying(500);
ALTER TABLE ai_tutor.student_quiz_attempt ADD COLUMN IF NOT EXISTS code character varying(500);
ALTER TABLE ai_tutor.student_quiz_attempt ADD COLUMN IF NOT EXISTS metadata_json jsonb;
ALTER TABLE ai_tutor.student_quiz_attempt ADD COLUMN IF NOT EXISTS name character varying(500);
ALTER TABLE ai_tutor.student_topic_mastery ADD COLUMN IF NOT EXISTS code character varying(500);
ALTER TABLE ai_tutor.student_topic_mastery ADD COLUMN IF NOT EXISTS metadata_json jsonb;
ALTER TABLE ai_tutor.student_topic_mastery ADD COLUMN IF NOT EXISTS name character varying(500);
ALTER TABLE ai_tutor.tutor_conversation ADD COLUMN IF NOT EXISTS code character varying(500);
ALTER TABLE ai_tutor.tutor_conversation ADD COLUMN IF NOT EXISTS metadata_json jsonb;
ALTER TABLE ai_tutor.tutor_conversation ADD COLUMN IF NOT EXISTS name character varying(500);
ALTER TABLE ai_tutor.tutor_message ADD COLUMN IF NOT EXISTS code character varying(500);
ALTER TABLE ai_tutor.tutor_message ADD COLUMN IF NOT EXISTS metadata_json jsonb;
ALTER TABLE ai_tutor.tutor_message ADD COLUMN IF NOT EXISTS name character varying(500);
ALTER TABLE ai_tutor.tutor_session ADD COLUMN IF NOT EXISTS code character varying(500);
ALTER TABLE ai_tutor.tutor_session ADD COLUMN IF NOT EXISTS metadata_json jsonb;
ALTER TABLE ai_tutor.tutor_session ADD COLUMN IF NOT EXISTS name character varying(500);
ALTER TABLE communication.conversation ADD COLUMN IF NOT EXISTS code character varying(500);
ALTER TABLE communication.conversation ADD COLUMN IF NOT EXISTS metadata_json jsonb;
ALTER TABLE communication.conversation ADD COLUMN IF NOT EXISTS name character varying(500);
ALTER TABLE communication.conversation_participant ADD COLUMN IF NOT EXISTS code character varying(500);
ALTER TABLE communication.conversation_participant ADD COLUMN IF NOT EXISTS conversation_participant_id uuid;
ALTER TABLE communication.conversation_participant ADD COLUMN IF NOT EXISTS metadata_json jsonb;
ALTER TABLE communication.conversation_participant ADD COLUMN IF NOT EXISTS name character varying(500);
ALTER TABLE communication.message ADD COLUMN IF NOT EXISTS code character varying(500);
ALTER TABLE communication.message ADD COLUMN IF NOT EXISTS metadata_json jsonb;
ALTER TABLE communication.message ADD COLUMN IF NOT EXISTS name character varying(500);
ALTER TABLE communication.message_receipt ADD COLUMN IF NOT EXISTS code character varying(500);
ALTER TABLE communication.message_receipt ADD COLUMN IF NOT EXISTS message_receipt_id uuid;
ALTER TABLE communication.message_receipt ADD COLUMN IF NOT EXISTS metadata_json jsonb;
ALTER TABLE communication.message_receipt ADD COLUMN IF NOT EXISTS name character varying(500);
ALTER TABLE communication.notification ADD COLUMN IF NOT EXISTS action_url character varying(500);
ALTER TABLE communication.notification ADD COLUMN IF NOT EXISTS is_read boolean;
ALTER TABLE communication.notification ADD COLUMN IF NOT EXISTS message character varying(500);
ALTER TABLE communication.notification ADD COLUMN IF NOT EXISTS occurred_at timestamp with time zone;
ALTER TABLE communication.notification ADD COLUMN IF NOT EXISTS priority character varying(500);
ALTER TABLE communication.notification ADD COLUMN IF NOT EXISTS read_at timestamp with time zone;
ALTER TABLE communication.notification ADD COLUMN IF NOT EXISTS recipient_user_id uuid;
ALTER TABLE communication.notification ADD COLUMN IF NOT EXISTS related_entity_id uuid;
ALTER TABLE communication.notification ADD COLUMN IF NOT EXISTS related_entity_type character varying(500);
ALTER TABLE communication.notification ADD COLUMN IF NOT EXISTS type character varying(500);
ALTER TABLE document.document_template ADD COLUMN IF NOT EXISTS metadata_json jsonb;
ALTER TABLE document.generated_document ADD COLUMN IF NOT EXISTS code character varying(500);
ALTER TABLE document.generated_document ADD COLUMN IF NOT EXISTS metadata_json jsonb;
ALTER TABLE document.generated_document ADD COLUMN IF NOT EXISTS name character varying(500);
ALTER TABLE exam.exam ADD COLUMN IF NOT EXISTS code character varying(500);
ALTER TABLE exam.exam ADD COLUMN IF NOT EXISTS metadata_json jsonb;
ALTER TABLE exam.exam_subject ADD COLUMN IF NOT EXISTS code character varying(500);
ALTER TABLE exam.exam_subject ADD COLUMN IF NOT EXISTS metadata_json jsonb;
ALTER TABLE exam.exam_subject ADD COLUMN IF NOT EXISTS name character varying(500);
ALTER TABLE exam.student_exam_result ADD COLUMN IF NOT EXISTS code character varying(500);
ALTER TABLE exam.student_exam_result ADD COLUMN IF NOT EXISTS metadata_json jsonb;
ALTER TABLE exam.student_exam_result ADD COLUMN IF NOT EXISTS name character varying(500);
ALTER TABLE finance.fee_type ADD COLUMN IF NOT EXISTS description character varying(500);
ALTER TABLE finance.fee_type ADD COLUMN IF NOT EXISTS frequency character varying(500);
ALTER TABLE finance.student_invoice ADD COLUMN IF NOT EXISTS code character varying(500);
ALTER TABLE finance.student_invoice ADD COLUMN IF NOT EXISTS metadata_json jsonb;
ALTER TABLE finance.student_invoice ADD COLUMN IF NOT EXISTS name character varying(500);
ALTER TABLE finance.student_payment ADD COLUMN IF NOT EXISTS code character varying(500);
ALTER TABLE finance.student_payment ADD COLUMN IF NOT EXISTS metadata_json jsonb;
ALTER TABLE finance.student_payment ADD COLUMN IF NOT EXISTS name character varying(500);
ALTER TABLE hr.candidate ADD COLUMN IF NOT EXISTS code character varying(500);
ALTER TABLE hr.candidate ADD COLUMN IF NOT EXISTS metadata_json jsonb;
ALTER TABLE hr.candidate ADD COLUMN IF NOT EXISTS name character varying(500);
ALTER TABLE hr.employee_compensation ADD COLUMN IF NOT EXISTS code character varying(500);
ALTER TABLE hr.employee_compensation ADD COLUMN IF NOT EXISTS metadata_json jsonb;
ALTER TABLE hr.employee_compensation ADD COLUMN IF NOT EXISTS name character varying(500);
ALTER TABLE hr.interview ADD COLUMN IF NOT EXISTS code character varying(500);
ALTER TABLE hr.interview ADD COLUMN IF NOT EXISTS metadata_json jsonb;
ALTER TABLE hr.interview ADD COLUMN IF NOT EXISTS name character varying(500);
ALTER TABLE hr.job ADD COLUMN IF NOT EXISTS metadata_json jsonb;
ALTER TABLE hr.job ADD COLUMN IF NOT EXISTS name character varying(500);
ALTER TABLE hr.job_grade ADD COLUMN IF NOT EXISTS metadata_json jsonb;
ALTER TABLE inventory.item ADD COLUMN IF NOT EXISTS metadata_json jsonb;
ALTER TABLE library.book ADD COLUMN IF NOT EXISTS code character varying(500);
ALTER TABLE library.book ADD COLUMN IF NOT EXISTS metadata_json jsonb;
ALTER TABLE library.book ADD COLUMN IF NOT EXISTS name character varying(500);
ALTER TABLE library.book_copy ADD COLUMN IF NOT EXISTS code character varying(500);
ALTER TABLE library.book_copy ADD COLUMN IF NOT EXISTS metadata_json jsonb;
ALTER TABLE library.book_copy ADD COLUMN IF NOT EXISTS name character varying(500);
ALTER TABLE library.book_loan ADD COLUMN IF NOT EXISTS code character varying(500);
ALTER TABLE library.book_loan ADD COLUMN IF NOT EXISTS metadata_json jsonb;
ALTER TABLE library.book_loan ADD COLUMN IF NOT EXISTS name character varying(500);
ALTER TABLE lms.academic_assignment ADD COLUMN IF NOT EXISTS code character varying(500);
ALTER TABLE lms.academic_assignment ADD COLUMN IF NOT EXISTS metadata_json jsonb;
ALTER TABLE lms.academic_assignment ADD COLUMN IF NOT EXISTS name character varying(500);
ALTER TABLE lms.student_assignment_submission ADD COLUMN IF NOT EXISTS code character varying(500);
ALTER TABLE lms.student_assignment_submission ADD COLUMN IF NOT EXISTS metadata_json jsonb;
ALTER TABLE lms.student_assignment_submission ADD COLUMN IF NOT EXISTS name character varying(500);
ALTER TABLE org.campus ADD COLUMN IF NOT EXISTS academic_system_id uuid;
ALTER TABLE org.campus ADD COLUMN IF NOT EXISTS branch_gender_type_id uuid;
ALTER TABLE org.campus ADD COLUMN IF NOT EXISTS branch_type character varying(500);
ALTER TABLE org.campus ADD COLUMN IF NOT EXISTS city character varying(500);
ALTER TABLE org.campus ADD COLUMN IF NOT EXISTS country character varying(500);
ALTER TABLE org.campus ADD COLUMN IF NOT EXISTS fax character varying(500);
ALTER TABLE org.campus ADD COLUMN IF NOT EXISTS logo_url character varying(500);
ALTER TABLE org.campus ADD COLUMN IF NOT EXISTS mobile character varying(500);
ALTER TABLE org.campus ADD COLUMN IF NOT EXISTS province character varying(500);
ALTER TABLE org.campus ADD COLUMN IF NOT EXISTS school_id uuid;
ALTER TABLE org.department ADD COLUMN IF NOT EXISTS campus_id uuid;
ALTER TABLE org.department ADD COLUMN IF NOT EXISTS email character varying(500);
ALTER TABLE org.department ADD COLUMN IF NOT EXISTS head_of_department_employee_id uuid;
ALTER TABLE org.department ADD COLUMN IF NOT EXISTS telephone character varying(500);
ALTER TABLE org.school ADD COLUMN IF NOT EXISTS fax character varying(500);
ALTER TABLE org.school ADD COLUMN IF NOT EXISTS province character varying(500);
ALTER TABLE payroll.payroll_run ADD COLUMN IF NOT EXISTS code character varying(500);
ALTER TABLE payroll.payroll_run ADD COLUMN IF NOT EXISTS metadata_json jsonb;
ALTER TABLE payroll.payroll_run ADD COLUMN IF NOT EXISTS name character varying(500);
ALTER TABLE student.student_guardian ADD COLUMN IF NOT EXISTS code character varying(500);
ALTER TABLE student.student_guardian ADD COLUMN IF NOT EXISTS metadata_json jsonb;
ALTER TABLE student.student_guardian ADD COLUMN IF NOT EXISTS name character varying(500);
ALTER TABLE teacher.leave_request ADD COLUMN IF NOT EXISTS code character varying(500);
ALTER TABLE teacher.leave_request ADD COLUMN IF NOT EXISTS metadata_json jsonb;
ALTER TABLE teacher.leave_request ADD COLUMN IF NOT EXISTS name character varying(500);
ALTER TABLE transport.route ADD COLUMN IF NOT EXISTS metadata_json jsonb;
ALTER TABLE transport.vehicle ADD COLUMN IF NOT EXISTS code character varying(500);
ALTER TABLE transport.vehicle ADD COLUMN IF NOT EXISTS metadata_json jsonb;
ALTER TABLE transport.vehicle ADD COLUMN IF NOT EXISTS name character varying(500);
COMMIT;
