<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="../SmartSchool.Application/SmartSchool.Application.csproj" />
    <ProjectReference Include="../SmartSchool.Infrastructure/SmartSchool.Infrastructure.csproj" />
    <ProjectReference Include="../SmartSchool.SharedKernel/SmartSchool.SharedKernel.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Hangfire.AspNetCore" />
    <PackageReference Include="Hangfire.PostgreSql" />
    <PackageReference Include="Hangfire.SqlServer" />
  </ItemGroup>

</Project>
