using SmartSchool.Modules.Academics.Contracts;
using SmartSchool.SharedKernel;
using SmartSchool.Application.Messaging;
using SmartSchool.Modules.Academics.Persistence;
using FluentValidation;
using SmartSchool.Modules.Academics.Features.AcademicSystem;
using SmartSchool.Modules.Academics.Features.AcademicYear;
using SmartSchool.Modules.Academics.Features.ClassSection;
using SmartSchool.Modules.Academics.Features.CourseOffering;
using SmartSchool.Modules.Academics.Features.CourseSelection;
using SmartSchool.Modules.Academics.Features.GradeLevel;
using SmartSchool.Modules.Academics.Features.Program;
using SmartSchool.Modules.Academics.Features.Subject;
using SmartSchool.Modules.Academics.Features.TeacherAssignment;
using SmartSchool.Modules.Academics.Features.Term;
using SmartSchool.Modules.Academics.Features.Timetable;
using SmartSchool.Modules.Academics.Features.TimetableEntry;

namespace SmartSchool.Modules.Academics;

public static class Module
{
    public static IServiceCollection AddAcademicsModule(
        this IServiceCollection services)
    {
        services.AddScoped<IAcademicSystemQuery, AcademicSystemQuery>();
        services.AddScoped<IAcademicSystemCommand, AcademicSystemCommand>();
        services.AddScoped<IAcademicYearQuery, AcademicYearQuery>();
        services.AddScoped<IAcademicYearCommand, AcademicYearCommand>();
        services.AddScoped<IClassSectionQuery, ClassSectionQuery>();
        services.AddScoped<IClassSectionCommand, ClassSectionCommand>();
        services.AddScoped<ICourseOfferingQuery, CourseOfferingQuery>();
        services.AddScoped<ICourseOfferingCommand, CourseOfferingCommand>();
        services.AddScoped<ICourseSelectionQuery, CourseSelectionQuery>();
        services.AddScoped<ICourseSelectionCommand, CourseSelectionCommand>();
        services.AddScoped<IGradeLevelQuery, GradeLevelQuery>();
        services.AddScoped<IGradeLevelCommand, GradeLevelCommand>();
        services.AddScoped<IProgramQuery, ProgramQuery>();
        services.AddScoped<IProgramCommand, ProgramCommand>();
        services.AddScoped<ISubjectQuery, SubjectQuery>();
        services.AddScoped<ISubjectCommand, SubjectCommand>();
        services.AddScoped<ITeacherAssignmentQuery, TeacherAssignmentQuery>();
        services.AddScoped<ITeacherAssignmentCommand, TeacherAssignmentCommand>();
        services.AddScoped<ITermQuery, TermQuery>();
        services.AddScoped<ITermCommand, TermCommand>();
        services.AddScoped<ITimetableQuery, TimetableQuery>();
        services.AddScoped<ITimetableCommand, TimetableCommand>();
        services.AddScoped<ITimetableEntryQuery, TimetableEntryQuery>();
        services.AddScoped<ITimetableEntryCommand, TimetableEntryCommand>();
        services.AddScoped<IValidator<CreateAcademicSystem.Request>, CreateAcademicSystem.Validator>();
        services.AddScoped<IValidator<UpdateAcademicSystem.Request>, UpdateAcademicSystem.Validator>();
        services.AddScoped<IValidator<CreateAcademicYear.Request>, CreateAcademicYear.Validator>();
        services.AddScoped<IValidator<UpdateAcademicYear.Request>, UpdateAcademicYear.Validator>();
        services.AddScoped<IValidator<CreateClassSection.Request>, CreateClassSection.Validator>();
        services.AddScoped<IValidator<UpdateClassSection.Request>, UpdateClassSection.Validator>();
        services.AddScoped<IValidator<CreateCourseOffering.Request>, CreateCourseOffering.Validator>();
        services.AddScoped<IValidator<UpdateCourseOffering.Request>, UpdateCourseOffering.Validator>();
        services.AddScoped<IValidator<CreateCourseSelection.Request>, CreateCourseSelection.Validator>();
        services.AddScoped<IValidator<UpdateCourseSelection.Request>, UpdateCourseSelection.Validator>();
        services.AddScoped<IValidator<CreateGradeLevel.Request>, CreateGradeLevel.Validator>();
        services.AddScoped<IValidator<UpdateGradeLevel.Request>, UpdateGradeLevel.Validator>();
        services.AddScoped<IValidator<CreateProgram.Request>, CreateProgram.Validator>();
        services.AddScoped<IValidator<UpdateProgram.Request>, UpdateProgram.Validator>();
        services.AddScoped<IValidator<CreateSubject.Request>, CreateSubject.Validator>();
        services.AddScoped<IValidator<UpdateSubject.Request>, UpdateSubject.Validator>();
        services.AddScoped<IValidator<CreateTeacherAssignment.Request>, CreateTeacherAssignment.Validator>();
        services.AddScoped<IValidator<UpdateTeacherAssignment.Request>, UpdateTeacherAssignment.Validator>();
        services.AddScoped<IValidator<CreateTerm.Request>, CreateTerm.Validator>();
        services.AddScoped<IValidator<UpdateTerm.Request>, UpdateTerm.Validator>();
        services.AddScoped<IValidator<CreateTimetable.Request>, CreateTimetable.Validator>();
        services.AddScoped<IValidator<UpdateTimetable.Request>, UpdateTimetable.Validator>();
        services.AddScoped<IValidator<CreateTimetableEntry.Request>, CreateTimetableEntry.Validator>();
        services.AddScoped<IValidator<UpdateTimetableEntry.Request>, UpdateTimetableEntry.Validator>();


        services.AddScoped<IRequestHandler<CreateAcademicSystem.Request, Result<AcademicSystemResponse>>, CreateAcademicSystem.Handler>();
        services.AddScoped<IRequestHandler<GetAcademicSystemById.Query, Result<AcademicSystemResponse>>, GetAcademicSystemById.Handler>();
        services.AddScoped<IRequestHandler<GetAcademicSystemPage.Query, Result<PagedResult<AcademicSystemResponse>>>, GetAcademicSystemPage.Handler>();
        services.AddScoped<IRequestHandler<UpdateAcademicSystem.Request, Result<AcademicSystemResponse>>, UpdateAcademicSystem.Handler>();
        services.AddScoped<IRequestHandler<DeleteAcademicSystem.Command, Result<DeleteAcademicSystem.Response>>, DeleteAcademicSystem.Handler>();
        services.AddScoped<IRequestHandler<CreateAcademicYear.Request, Result<AcademicYearResponse>>, CreateAcademicYear.Handler>();
        services.AddScoped<IRequestHandler<GetAcademicYearById.Query, Result<AcademicYearResponse>>, GetAcademicYearById.Handler>();
        services.AddScoped<IRequestHandler<GetAcademicYearPage.Query, Result<PagedResult<AcademicYearResponse>>>, GetAcademicYearPage.Handler>();
        services.AddScoped<IRequestHandler<UpdateAcademicYear.Request, Result<AcademicYearResponse>>, UpdateAcademicYear.Handler>();
        services.AddScoped<IRequestHandler<DeleteAcademicYear.Command, Result<DeleteAcademicYear.Response>>, DeleteAcademicYear.Handler>();
        services.AddScoped<IRequestHandler<CreateClassSection.Request, Result<ClassSectionResponse>>, CreateClassSection.Handler>();
        services.AddScoped<IRequestHandler<GetClassSectionById.Query, Result<ClassSectionResponse>>, GetClassSectionById.Handler>();
        services.AddScoped<IRequestHandler<GetClassSectionPage.Query, Result<PagedResult<ClassSectionResponse>>>, GetClassSectionPage.Handler>();
        services.AddScoped<IRequestHandler<UpdateClassSection.Request, Result<ClassSectionResponse>>, UpdateClassSection.Handler>();
        services.AddScoped<IRequestHandler<DeleteClassSection.Command, Result<DeleteClassSection.Response>>, DeleteClassSection.Handler>();
        services.AddScoped<IRequestHandler<CreateCourseOffering.Request, Result<CourseOfferingResponse>>, CreateCourseOffering.Handler>();
        services.AddScoped<IRequestHandler<GetCourseOfferingById.Query, Result<CourseOfferingResponse>>, GetCourseOfferingById.Handler>();
        services.AddScoped<IRequestHandler<GetCourseOfferingPage.Query, Result<PagedResult<CourseOfferingResponse>>>, GetCourseOfferingPage.Handler>();
        services.AddScoped<IRequestHandler<UpdateCourseOffering.Request, Result<CourseOfferingResponse>>, UpdateCourseOffering.Handler>();
        services.AddScoped<IRequestHandler<DeleteCourseOffering.Command, Result<DeleteCourseOffering.Response>>, DeleteCourseOffering.Handler>();
        services.AddScoped<IRequestHandler<CreateCourseSelection.Request, Result<CourseSelectionResponse>>, CreateCourseSelection.Handler>();
        services.AddScoped<IRequestHandler<GetCourseSelectionById.Query, Result<CourseSelectionResponse>>, GetCourseSelectionById.Handler>();
        services.AddScoped<IRequestHandler<GetCourseSelectionPage.Query, Result<PagedResult<CourseSelectionResponse>>>, GetCourseSelectionPage.Handler>();
        services.AddScoped<IRequestHandler<UpdateCourseSelection.Request, Result<CourseSelectionResponse>>, UpdateCourseSelection.Handler>();
        services.AddScoped<IRequestHandler<DeleteCourseSelection.Command, Result<DeleteCourseSelection.Response>>, DeleteCourseSelection.Handler>();
        services.AddScoped<IRequestHandler<CreateGradeLevel.Request, Result<GradeLevelResponse>>, CreateGradeLevel.Handler>();
        services.AddScoped<IRequestHandler<GetGradeLevelById.Query, Result<GradeLevelResponse>>, GetGradeLevelById.Handler>();
        services.AddScoped<IRequestHandler<GetGradeLevelPage.Query, Result<PagedResult<GradeLevelResponse>>>, GetGradeLevelPage.Handler>();
        services.AddScoped<IRequestHandler<UpdateGradeLevel.Request, Result<GradeLevelResponse>>, UpdateGradeLevel.Handler>();
        services.AddScoped<IRequestHandler<DeleteGradeLevel.Command, Result<DeleteGradeLevel.Response>>, DeleteGradeLevel.Handler>();
        services.AddScoped<IRequestHandler<CreateProgram.Request, Result<ProgramResponse>>, CreateProgram.Handler>();
        services.AddScoped<IRequestHandler<GetProgramById.Query, Result<ProgramResponse>>, GetProgramById.Handler>();
        services.AddScoped<IRequestHandler<GetProgramPage.Query, Result<PagedResult<ProgramResponse>>>, GetProgramPage.Handler>();
        services.AddScoped<IRequestHandler<UpdateProgram.Request, Result<ProgramResponse>>, UpdateProgram.Handler>();
        services.AddScoped<IRequestHandler<DeleteProgram.Command, Result<DeleteProgram.Response>>, DeleteProgram.Handler>();
        services.AddScoped<IRequestHandler<CreateSubject.Request, Result<SubjectResponse>>, CreateSubject.Handler>();
        services.AddScoped<IRequestHandler<GetSubjectById.Query, Result<SubjectResponse>>, GetSubjectById.Handler>();
        services.AddScoped<IRequestHandler<GetSubjectPage.Query, Result<PagedResult<SubjectResponse>>>, GetSubjectPage.Handler>();
        services.AddScoped<IRequestHandler<UpdateSubject.Request, Result<SubjectResponse>>, UpdateSubject.Handler>();
        services.AddScoped<IRequestHandler<DeleteSubject.Command, Result<DeleteSubject.Response>>, DeleteSubject.Handler>();
        services.AddScoped<IRequestHandler<CreateTeacherAssignment.Request, Result<TeacherAssignmentResponse>>, CreateTeacherAssignment.Handler>();
        services.AddScoped<IRequestHandler<GetTeacherAssignmentById.Query, Result<TeacherAssignmentResponse>>, GetTeacherAssignmentById.Handler>();
        services.AddScoped<IRequestHandler<GetTeacherAssignmentPage.Query, Result<PagedResult<TeacherAssignmentResponse>>>, GetTeacherAssignmentPage.Handler>();
        services.AddScoped<IRequestHandler<UpdateTeacherAssignment.Request, Result<TeacherAssignmentResponse>>, UpdateTeacherAssignment.Handler>();
        services.AddScoped<IRequestHandler<DeleteTeacherAssignment.Command, Result<DeleteTeacherAssignment.Response>>, DeleteTeacherAssignment.Handler>();
        services.AddScoped<IRequestHandler<CreateTerm.Request, Result<TermResponse>>, CreateTerm.Handler>();
        services.AddScoped<IRequestHandler<GetTermById.Query, Result<TermResponse>>, GetTermById.Handler>();
        services.AddScoped<IRequestHandler<GetTermPage.Query, Result<PagedResult<TermResponse>>>, GetTermPage.Handler>();
        services.AddScoped<IRequestHandler<UpdateTerm.Request, Result<TermResponse>>, UpdateTerm.Handler>();
        services.AddScoped<IRequestHandler<DeleteTerm.Command, Result<DeleteTerm.Response>>, DeleteTerm.Handler>();
        services.AddScoped<IRequestHandler<CreateTimetable.Request, Result<TimetableResponse>>, CreateTimetable.Handler>();
        services.AddScoped<IRequestHandler<GetTimetableById.Query, Result<TimetableResponse>>, GetTimetableById.Handler>();
        services.AddScoped<IRequestHandler<GetTimetablePage.Query, Result<PagedResult<TimetableResponse>>>, GetTimetablePage.Handler>();
        services.AddScoped<IRequestHandler<UpdateTimetable.Request, Result<TimetableResponse>>, UpdateTimetable.Handler>();
        services.AddScoped<IRequestHandler<DeleteTimetable.Command, Result<DeleteTimetable.Response>>, DeleteTimetable.Handler>();
        services.AddScoped<IRequestHandler<CreateTimetableEntry.Request, Result<TimetableEntryResponse>>, CreateTimetableEntry.Handler>();
        services.AddScoped<IRequestHandler<GetTimetableEntryById.Query, Result<TimetableEntryResponse>>, GetTimetableEntryById.Handler>();
        services.AddScoped<IRequestHandler<GetTimetableEntryPage.Query, Result<PagedResult<TimetableEntryResponse>>>, GetTimetableEntryPage.Handler>();
        services.AddScoped<IRequestHandler<UpdateTimetableEntry.Request, Result<TimetableEntryResponse>>, UpdateTimetableEntry.Handler>();
        services.AddScoped<IRequestHandler<DeleteTimetableEntry.Command, Result<DeleteTimetableEntry.Response>>, DeleteTimetableEntry.Handler>();

        return services;
    }

    public static IEndpointRouteBuilder MapAcademicsEndpoints(
        this IEndpointRouteBuilder endpoints)
    {
        CreateAcademicSystem.MapEndpoint(endpoints);
        GetAcademicSystemById.MapEndpoint(endpoints);
        GetAcademicSystemPage.MapEndpoint(endpoints);
        UpdateAcademicSystem.MapEndpoint(endpoints);
        DeleteAcademicSystem.MapEndpoint(endpoints);
        CreateAcademicYear.MapEndpoint(endpoints);
        GetAcademicYearById.MapEndpoint(endpoints);
        GetAcademicYearPage.MapEndpoint(endpoints);
        UpdateAcademicYear.MapEndpoint(endpoints);
        DeleteAcademicYear.MapEndpoint(endpoints);
        CreateClassSection.MapEndpoint(endpoints);
        GetClassSectionById.MapEndpoint(endpoints);
        GetClassSectionPage.MapEndpoint(endpoints);
        UpdateClassSection.MapEndpoint(endpoints);
        DeleteClassSection.MapEndpoint(endpoints);
        CreateCourseOffering.MapEndpoint(endpoints);
        GetCourseOfferingById.MapEndpoint(endpoints);
        GetCourseOfferingPage.MapEndpoint(endpoints);
        UpdateCourseOffering.MapEndpoint(endpoints);
        DeleteCourseOffering.MapEndpoint(endpoints);
        CreateCourseSelection.MapEndpoint(endpoints);
        GetCourseSelectionById.MapEndpoint(endpoints);
        GetCourseSelectionPage.MapEndpoint(endpoints);
        UpdateCourseSelection.MapEndpoint(endpoints);
        DeleteCourseSelection.MapEndpoint(endpoints);
        CreateGradeLevel.MapEndpoint(endpoints);
        GetGradeLevelById.MapEndpoint(endpoints);
        GetGradeLevelPage.MapEndpoint(endpoints);
        UpdateGradeLevel.MapEndpoint(endpoints);
        DeleteGradeLevel.MapEndpoint(endpoints);
        CreateProgram.MapEndpoint(endpoints);
        GetProgramById.MapEndpoint(endpoints);
        GetProgramPage.MapEndpoint(endpoints);
        UpdateProgram.MapEndpoint(endpoints);
        DeleteProgram.MapEndpoint(endpoints);
        CreateSubject.MapEndpoint(endpoints);
        GetSubjectById.MapEndpoint(endpoints);
        GetSubjectPage.MapEndpoint(endpoints);
        UpdateSubject.MapEndpoint(endpoints);
        DeleteSubject.MapEndpoint(endpoints);
        CreateTeacherAssignment.MapEndpoint(endpoints);
        GetTeacherAssignmentById.MapEndpoint(endpoints);
        GetTeacherAssignmentPage.MapEndpoint(endpoints);
        UpdateTeacherAssignment.MapEndpoint(endpoints);
        DeleteTeacherAssignment.MapEndpoint(endpoints);
        CreateTerm.MapEndpoint(endpoints);
        GetTermById.MapEndpoint(endpoints);
        GetTermPage.MapEndpoint(endpoints);
        UpdateTerm.MapEndpoint(endpoints);
        DeleteTerm.MapEndpoint(endpoints);
        CreateTimetable.MapEndpoint(endpoints);
        GetTimetableById.MapEndpoint(endpoints);
        GetTimetablePage.MapEndpoint(endpoints);
        UpdateTimetable.MapEndpoint(endpoints);
        DeleteTimetable.MapEndpoint(endpoints);
        CreateTimetableEntry.MapEndpoint(endpoints);
        GetTimetableEntryById.MapEndpoint(endpoints);
        GetTimetableEntryPage.MapEndpoint(endpoints);
        UpdateTimetableEntry.MapEndpoint(endpoints);
        DeleteTimetableEntry.MapEndpoint(endpoints);

        return endpoints;
    }
}
