BEGIN;
CREATE TABLE IF NOT EXISTS academic.class (class_id uuid PRIMARY KEY DEFAULT gen_random_uuid(), tenant_id uuid NOT NULL REFERENCES saas.tenant(tenant_id), school_id uuid NOT NULL REFERENCES org.school(school_id), branch_id uuid NOT NULL REFERENCES org.campus(campus_id), code varchar(30) NOT NULL, name varchar(100) NOT NULL, sort_order integer NOT NULL DEFAULT 0, is_active boolean NOT NULL DEFAULT true, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz, row_version bytea NOT NULL DEFAULT public.gen_random_bytes(8), UNIQUE(branch_id,code));
ALTER TABLE academic.section ADD COLUMN IF NOT EXISTS branch_id uuid REFERENCES org.campus(campus_id);
ALTER TABLE academic.section ADD COLUMN IF NOT EXISTS class_id uuid REFERENCES academic.class(class_id);
ALTER TABLE academic.academic_year ADD COLUMN IF NOT EXISTS school_id uuid REFERENCES org.school(school_id);
ALTER TABLE academic.academic_year ADD COLUMN IF NOT EXISTS branch_id uuid REFERENCES org.campus(campus_id);
ALTER TABLE academic.academic_year ADD COLUMN IF NOT EXISTS code varchar(30);
UPDATE academic.academic_year SET branch_id=campus_id WHERE branch_id IS NULL;
UPDATE academic.academic_year SET school_id=c.school_id FROM org.campus c WHERE academic.academic_year.campus_id=c.campus_id AND academic.academic_year.school_id IS NULL;
UPDATE academic.academic_year SET code=replace(name,'/','-') WHERE code IS NULL;
ALTER TABLE admission.student_application ADD COLUMN IF NOT EXISTS class_id uuid REFERENCES academic.class(class_id);
ALTER TABLE admission.student_application ADD COLUMN IF NOT EXISTS section_id uuid REFERENCES academic.section(section_id);
ALTER TABLE admission.admission_criteria ADD COLUMN IF NOT EXISTS class_id uuid REFERENCES academic.class(class_id);
ALTER TABLE academic.class_section ADD COLUMN IF NOT EXISTS class_id uuid REFERENCES academic.class(class_id);
CREATE INDEX IF NOT EXISTS ix_academic_year_branch ON academic.academic_year(tenant_id,branch_id);
CREATE INDEX IF NOT EXISTS ix_class_branch ON academic.class(tenant_id,branch_id);
CREATE INDEX IF NOT EXISTS ix_section_branch_class ON academic.section(tenant_id,branch_id,class_id);
COMMIT;
