-- v61: schemas added to configurations that previously mapped to public.
-- Review in staging before production.
CREATE SCHEMA IF NOT EXISTS academics;
CREATE SCHEMA IF NOT EXISTS transport;
CREATE SCHEMA IF NOT EXISTS examinations;
CREATE SCHEMA IF NOT EXISTS workflow;
CREATE SCHEMA IF NOT EXISTS payroll;
CREATE SCHEMA IF NOT EXISTS communication;
CREATE SCHEMA IF NOT EXISTS tenancy;
CREATE SCHEMA IF NOT EXISTS admissions;
CREATE SCHEMA IF NOT EXISTS documents;
CREATE SCHEMA IF NOT EXISTS ai_prediction;
CREATE SCHEMA IF NOT EXISTS ai_parent;
CREATE SCHEMA IF NOT EXISTS students;
CREATE SCHEMA IF NOT EXISTS ai_core;
CREATE SCHEMA IF NOT EXISTS finance;
CREATE SCHEMA IF NOT EXISTS ai_inquiry;
CREATE SCHEMA IF NOT EXISTS hr;
CREATE SCHEMA IF NOT EXISTS identity;
CREATE SCHEMA IF NOT EXISTS library;
CREATE SCHEMA IF NOT EXISTS audit;
CREATE SCHEMA IF NOT EXISTS activities;
CREATE SCHEMA IF NOT EXISTS inventory;
CREATE SCHEMA IF NOT EXISTS learning;
CREATE SCHEMA IF NOT EXISTS organization;
CREATE SCHEMA IF NOT EXISTS ai_tutor;

ALTER TABLE IF EXISTS public."Subscription" SET SCHEMA tenancy;
ALTER TABLE IF EXISTS public."Tenant" SET SCHEMA tenancy;
ALTER TABLE IF EXISTS public."CampusBranding" SET SCHEMA tenancy;
ALTER TABLE IF EXISTS public."StudentPerformancePrediction" SET SCHEMA ai_prediction;
ALTER TABLE IF EXISTS public."ClassPerformanceInsight" SET SCHEMA ai_prediction;
ALTER TABLE IF EXISTS public."TeachingRecommendation" SET SCHEMA ai_prediction;
ALTER TABLE IF EXISTS public."PredictionEvidence" SET SCHEMA ai_prediction;
ALTER TABLE IF EXISTS public."PredictionEvaluation" SET SCHEMA ai_prediction;
ALTER TABLE IF EXISTS public."TopicPerformanceInsight" SET SCHEMA ai_prediction;
ALTER TABLE IF EXISTS public."StudentIntervention" SET SCHEMA ai_prediction;
ALTER TABLE IF EXISTS public."PredictionModel" SET SCHEMA ai_prediction;
ALTER TABLE IF EXISTS public."TeacherDirectoryRead" SET SCHEMA hr;
ALTER TABLE IF EXISTS public."Candidate" SET SCHEMA hr;
ALTER TABLE IF EXISTS public."EmployeeDocument" SET SCHEMA hr;
ALTER TABLE IF EXISTS public."JobGrade" SET SCHEMA hr;
ALTER TABLE IF EXISTS public."Resume" SET SCHEMA hr;
ALTER TABLE IF EXISTS public."TeacherProfile" SET SCHEMA hr;
ALTER TABLE IF EXISTS public."TeacherDocument" SET SCHEMA hr;
ALTER TABLE IF EXISTS public."PayrollProfile" SET SCHEMA hr;
ALTER TABLE IF EXISTS public."Job" SET SCHEMA hr;
ALTER TABLE IF EXISTS public."CandidateDocument" SET SCHEMA hr;
ALTER TABLE IF EXISTS public."Interview" SET SCHEMA hr;
ALTER TABLE IF EXISTS public."Position" SET SCHEMA hr;
ALTER TABLE IF EXISTS public."EmploymentHistory" SET SCHEMA hr;
ALTER TABLE IF EXISTS public."LeaveRequest" SET SCHEMA hr;
ALTER TABLE IF EXISTS public."RoleAssignment" SET SCHEMA identity;
ALTER TABLE IF EXISTS public."UserProfile" SET SCHEMA identity;
